### ISSUE TITLE
Support for .fi domains

### ISSUE THREAD

**Issue by a-stankevich** [shlin168/go-whois#1]
.fi domains can't be parsed due to error:
`parsing time "" as "2006-01-02T15:04:05+00:00": cannot parse "" as "2006"`

[Example whois response](https://gist.github.com/a-stankevich/f32104968cde16149e74f5b64dbe1324)

**Comment by shlin168** [comment]
Hi,

Thanks for reporting the issue, `.fi` domain parser is added in 130768681b663aaffecfe9a3c057dad699c4996d. 

The tests are passed in my local environment, while it looks like there's some temporarily problem in GitHub Actions so the workflow has not been triggered. I will follow up with this problem later.

* [githubstatus](https://www.githubstatus.com)

**Comment by a-stankevich** [comment]
Wow, that was incredibly fast! Thank you!
